### ISSUE TITLE
Possible to make media_container public?

### ISSUE THREAD

**Issue by doccccccccc** [andrey-yantsen/plex-api.rs#509]
So I can reuse the structs in my project

**Comment by andrey-yantsen** [comment]
@doccccccccc, it shouldn't be a problem, but can you tell me more about your use case? Are you sure you want to use the crate, which has 17 direct dependencies (and a ton of indirect ones) only for the `media_container`?

Also, as @Mossop has noted in #508, the current internal structs are unstable, and it's dangerous to rely on them externally.

It might be worth moving the structs and encoding/decoding logic to another crate, but I'm not sure when I'll be able to invest the time in it.
